_format_version: "3.0"
consumers:
  - keyauth_credentials:
      - key: DEMO-KEY-123456
    username: demo
services:
  - connect_timeout: 60000
    enabled: true
    host: albums
    name: albums
    plugins:
      - config:
          credentials: true
          exposed_headers: null
          headers:
            - Authorization
            - Content-Type
          max_age: null
          methods:
            - GET
            - POST
            - DELETE
            - PUT
            - PATCH
            - OPTIONS
            - HEAD
          origins:
            - "*"
          preflight_continue: false
          private_network: false
        enabled: true
        name: cors
        protocols:
          - grpc
          - grpcs
          - http
          - https
      - config:
          anonymous: null
          hide_credentials: false
          key_in_body: false
          key_in_header: true
          key_in_query: true
          key_names:
            - apikey
          realm: null
          run_on_preflight: true
        enabled: true
        name: key-auth
        protocols:
          - grpc
          - grpcs
          - http
          - https
    port: 8080
    protocol: http
    read_timeout: 60000
    retries: 5
    routes:
      - https_redirect_status_code: 426
        name: albums-api
        path_handling: v0
        paths:
          - /albums
        preserve_host: false
        protocols:
          - http
          - https
        regex_priority: 0
        request_buffering: true
        response_buffering: true
        strip_path: true
    write_timeout: 60000

  - connect_timeout: 60000
    enabled: true
    host: user
    name: user
    plugins:
      - config:
          credentials: true
          exposed_headers: null
          headers:
            - Authorization
            - Content-Type
          max_age: null
          methods:
            - GET
            - POST
            - DELETE
            - PUT
            - PATCH
            - OPTIONS
            - HEAD
          origins:
            - "*"
          preflight_continue: false
          private_network: false
        enabled: true
        name: cors
        protocols:
          - grpc
          - grpcs
          - http
          - https
    port: 8080
    protocol: http
    read_timeout: 60000
    retries: 5
    routes:
      - https_redirect_status_code: 426
        name: user-api
        path_handling: v0
        paths:
          - /user
        preserve_host: false
        protocols:
          - http
          - https
        regex_priority: 0
        request_buffering: true
        response_buffering: true
        strip_path: true
    write_timeout: 60000

upstreams:
  - algorithm: round-robin
    hash_fallback: none
    hash_on: none
    hash_on_cookie_path: /
    healthchecks:
      active:
        concurrency: 10
        healthy:
          http_statuses:
            - 200
            - 302
          interval: 0
          successes: 0
        http_path: /
        https_verify_certificate: true
        timeout: 1
        type: http
        unhealthy:
          http_failures: 0
          http_statuses:
            - 429
            - 404
            - 500
            - 501
            - 502
            - 503
            - 504
            - 505
          interval: 0
          tcp_failures: 0
          timeouts: 0
      passive:
        healthy:
          http_statuses:
            - 200
            - 201
            - 202
            - 203
            - 204
            - 205
            - 206
            - 207
            - 208
            - 226
            - 300
            - 301
            - 302
            - 303
            - 304
            - 305
            - 306
            - 307
            - 308
          successes: 0
        type: http
        unhealthy:
          http_failures: 0
          http_statuses:
            - 429
            - 500
            - 503
          tcp_failures: 0
          timeouts: 0
      threshold: 0
    name: albums_upstream
    slots: 10000
    targets:
      - target: albums-1:8080
        weight: 100
    use_srv_name: false
